CREATE TABLE IF NOT EXISTS users(
    id bigserial PRIMARY KEY,
    email VARCHAR(300) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);